version: "3"
services:
  sandbox:
    image: yolanmq/sandbox
    container_name: sandbox
    build: .
    user: "unprivileged"
    working_dir: "/home/unprivileged"
    volumes:
      - ./shared:/home/unprivileged/shared
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-./shared/tests/test_all.sh}"
      interval: "60s"
      timeout: "3s"
      retries: 3


