version: '3.7'
services:
  db:
    hostname: db
    container_name: backend-mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./docker/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./docker/database:/database/db
    restart: always
    env_file:
      - database.env
