version: '3.7'
services:
  db:
    hostname: db
    container_name: backend-mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    restart: always
    env_file:
      - database.env

